version: '3.3'

services:
  nginx:
    build:
      context: ./nginx-custom
    ports:
      - "80:80"
    depends_on:
      - tomcat

  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - ./webapp:/usr/local/tomcat/webapps
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=myappdb
      - MYSQL_USER=myappuser
      - MYSQL_PASSWORD=myapppass
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest


